# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'WeatherTracker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WeatherTracker

   pod 'Alamofire', '~> 5.0.0.beta.1'
   pod 'SwiftyJSON'
end
